[package]
authors = ["James Wilson <james.wilson@prowler.io>"]
edition = "2018"
name = "aoc2020"
version = "0.1.0"

[lib]
name = "shared"
path = "src/shared/lib.rs"

[dependencies]
anyhow = "1.0.34"
once_cell = "1.5.2"
regex = "1.4.2"
structopt = "0.3.21"

